spring.application.name=DriveFast

spring.datasource.url=jdbc:postgresql://localhost:3306/DriveFast
spring.datasource.username=root
spring.datasource.password=mysqlPW

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

